# anything related to audio I/O

# something like this:
def get_wav_params(filename): ...
def read_wav_frames(filename, chunk_size): ...
def microphone_frames(chunk_size): ...
def play_audio_frame(frame): ...

# at some pointt we may have to implement mode validation I think its best if its done here