# anything RTP + RTCP relatedS

def build_rtp_packet(payload, seq, timestamp, ssrc, payload_type=0): ...
def parse_rtp_packet(data): ...
def build_rtcp_sr(ssrc, packet_count, octet_count): ...
def rtp_send_loop(sock, remote_addr, audio_source, stop_event): ...
def rtp_receive_loop(sock, audio_player, stop_event): ...
def rtcp_send_loop(sock, remote_addr, stop_event, stats): ...