# anything SIP + SDP related

# something like this:
def _build_message(): ...
def build_sdp(): ...
def parse_sdp(): ...
def parse_sip_message(): ...
def build_invite(): ...
def build_200_ok(): ...
def build_ack(): ...
def build_bye(): ...