# RTP/RTCP protocol constants

RTP_VERSION = 2
RTP_HEADER_SIZE = 12
RTCP_SR_PACKET_TYPE = 200
RTCP_RR_PACKET_TYPE = 201
NTP_UNIX_EPOCH_OFFSET = 2_208_988_800
JITTER_BUFFER_SIZE = 2  # number of packets to buffer

# SDP constants

DEFAULT_CODEC = "PCMU"
DEFAULT_PAYLOAD_TYPE = 0
DEFAULT_SAMPLE_RATE = 8000
DEFAULT_CHANNELS = 1
